### ISSUE TITLE
permission denied, mkdir '/bitnami/nginx'

### ISSUE THREAD

**Issue by daiing** [bitnami/bitnami-docker-nginx#102]
when I want to use Full configuration, then I get the wrong msg:
[root@ydpt docker]# docker run --restart=always --name app-nginx   -v /docker/nginx/nginx-persistence:/bitnami   bitnami/nginx:latest
Welcome to the Bitnami nginx container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues
nami    INFO  Initializing nginx
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/nginx'

**Comment by tompizmor** [comment]
Hello @daiing,

The nginx container was moved to a non-root approach some time ago so that should be the cause of your issue.
Before mounting your local volume in the container you may need to adjust the permissions. Could you try with this command:

```
sudo chmod -R g+rwX /docker/nginx/nginx-persistence
```

If that does not work could you try with: 

```
sudo chown -R 1001:1001 /docker/nginx/nginx-persistence
```

A similar error has been widely discussed in the mariadb repo: https://github.com/bitnami/bitnami-docker-mariadb/issues/136#issuecomment-354644226

**Comment by daiing** [comment]
It's OK, thank you very much
