### ISSUE TITLE
Better solution to serve both static and dynamic content via Nginx from php-fpm container?

### ISSUE THREAD

**Issue by 1212087** [bitnami/bitnami-docker-nginx#152]
Hi Binamit,

I have the same question as [this issue](https://github.com/bitnami/bitnami-docker-nginx/issues/138), @juan131 answered a good solution, but there is one problem: when you re-create your containers from a newer version of the image (image also contain some public files such as JS, CSS bundle...), these new files will be replaced by the old ones from the mounted volume. 

I could delete the volume before re-creating the containers to make sure that all new files from phpfpm -> volume -> nginx, but does anyone has better solutions for this?

**Comment by juan131** [comment]
Hi @1212087 

So basically want to avoid overriding the static files that comes by default with the NGINX container right? I mean, these ones:

```console
$ docker run --rm -it bitnami/nginx ls -la /app
...
total 16
drwxr-xr-x 2 root root 4096 Feb 22 19:37 .
drwxr-xr-x 1 root root 4096 Feb 24 07:47 ..
-rw-r--r-- 1 root root  494 Feb 22 19:31 50x.html
```

Or are you using a custom image? I want to have a clear picture of what you're trying to achieve.

**Comment by 1212087** [comment]
Hi @juan131, 

This is my structure now 
![image](https://user-images.githubusercontent.com/17928753/109002965-73571600-76d9-11eb-9b88-ff804b1fcdb1.png)

I'm using a custom Nginx and PHP dockerfile, both of them will pull the latest Laravel code from GitHub when building a new image. Sometimes, I need to rebuild some Laravel public JS, CSS files and push them to GitHub.

At the building stage, both Nginx and PHP will pull new code from Github, so the images now have new JS, CSS files.

At the deployment stage, all these new JS, CSS files are replaced by the old ones which were mounted out at the previous deployment :( this is the problem.

When the PHP container running, it also generates some new files to the public folder, such as sitemap and sitemap index, how can I send these files to the Nginx container so that I can access them from the browser (example.com/new-generate-sitemap.xml)? I think my current approach is not good, do you have any better solution?

Sorry, my English is not good, please ask me anything if you don't understand.

**Comment by juan131** [comment]
Hi @1212087 

There's a conceptual issue here.

The solution I proposed at [this issue](https://github.com/bitnami/bitnami-docker-nginx/issues/138) just provides a way to share the app code between the NGINX and the PHP container, **assuming the development of this code is externally managed by the developer**. In other words, the developer is responsible on updating the code on the shared volume, the PHP and NGINX images just provide the capability to use that code but don't ship it.

In your case, **the images contains the application code** and **updating the code implies updating images** (this is a valid approach too). In principle, there's no need to use a volume to share the code since the images already ship it. 

However, you mentioned that, during the initialisation of the PHP container it generates some files that needs to be shared with NGINX. In this case, I'll use a volume to share those generated files (exclusively) keeping the rest of the code out of the volume. Then, I'll ensure that the PHP overwrites whatever files are saved on the volume from previous deployments, so every-time this container is started they're updated.

**Comment by 1212087** [comment]
Thank you for your answer @juan131, How do you think about this?

I'll use a volume to store all generated files from PHP container, then Nginx container will mount these files to its public/sitemaps folder. I also redirect all /sitemap.xml request to public/sitemaps folder too, so that Nginx can servers these files to the browser :) I think this is a better solution
 
![image](https://user-images.githubusercontent.com/17928753/109332288-79dbbe00-7890-11eb-9c9f-1754081dfb39.png)

**Comment by juan131** [comment]
Hi @1212087 

I think that approach should work, yes. Did you already test it?
It's important that the PHP container is the only one that writes the "sitemaps" volume, keeping the NGINX container as read-only.

**Comment by 1212087** [comment]
Hi @juan131 

Yes, it worked, Nginx just only serves static files, it does not contain any PHP files.
But this model will not work if Nginx and PHP container was deployed on different servers because docker volume can not be mounted between different servers.

Anyway, I'm not sure this is a valid approach or not, but it worked, at least now.

**Comment by juan131** [comment]
Hi @1212087 

> Yes, it worked, Nginx just only serves static files, it does not contain any PHP files.

Great!

> But this model will not work if Nginx and PHP container was deployed on different servers because docker volume can not be mounted between different servers.

Correct, in that case you'll have to use some kind of NFS server (or similar solution) to provide you the volume used between PHP and NGINX containers to share files.
