### ISSUE TITLE
nginx stack have not php?

### ISSUE THREAD

**Issue by lifeblood** [bitnami/bitnami-docker-nginx#29]

**Comment by chipironcin** [comment]
Hi @lifeblood 
Our Nginx image only ships Nginx to make it as slim as possible.
It lets you serve HTML files.

If you want to interpret php scripts you may want to use our [PHP-FPM image](https://github.com/bitnami/bitnami-docker-php-fpm)
In order to serve a webpage with PHP code you may want to follow our guide:
https://github.com/bitnami/bitnami-docker-php-fpm#user-content-serving-your-php-app-through-an-nginx-frontend.

I hope this information helps you out.
Do not hesitate in opening a new issue if you find something wrong with our images and feel free to open Pull Requests if you want to add features or provide a fix :)

**Comment by prydonius** [comment]
Closing this issue, @lifeblood feel free to reopen or file a new issue if you have any other questions.
