### ISSUE TITLE
directory index of "/opt/bitnami/nginx/html/" is forbidden

### ISSUE THREAD

**Issue by sas05** [bitnami/bitnami-docker-nginx#31]
I have use all default from documentation.

**Comment by chipironcin** [comment]
Hi @sas05 
Could you provide more information on your issue? Like steps on how to reproduce it, expected behaviour and what actually happened.

Thanks

**Comment by sameersbn** [comment]
@sas05 I think the issue you are seeing is the same as discussed here https://github.com/bitnami/bitnami-docker-apache/issues/21. If it's indeed the issue, then there is little to nothing that we can do to fix it since it's external to the image.

The linked thread mentions some possible resolution. Please do take a look. 

If at all the issue your facing is not the same (or related), I'd request you to please share some details of your usage. Information that would prove to be useful for us to replicate and debug the issue includes the `docker run` command, output of `docker info` and `docker version`, host os, let us know if you are using virtual machines or docker-machine, etc.

**Comment by sas05** [comment]
Hi Guys, 

As I said I just use the defaults docker run commands from the documentations. today I have also tried with nginx official image that also has the same problem. 

docker version and info is upto date.

**Comment by sas05** [comment]
Containers: 12
 Running: 2
 Paused: 0
 Stopped: 10
Images: 3
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 48
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.10.3 (TCL 6.4.1); master : 625117e - Thu Mar 10 22:09:02 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: RYIW:BZJH:AJRA:J765:EP3A:WP66:WGNO:5GH6:JBMW:U4ZK:KE5J:UYLQ
Debug mode (server): true
 File Descriptors: 22
 Goroutines: 37
 System Time: 2016-04-06T14:15:49.344431331Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

**Comment by sas05** [comment]
ok I found it fixed with official nginx docker. I think bitnami nginx will also work.

Thank you guys for giving your time. I appreciate

**Comment by sameersbn** [comment]
@sas05 could you please share the resolution in the interest of other users?

**Comment by sas05** [comment]
Hi @sameersbn I have did anything with bitnami images. I pulled the official nginx and php image. I did one mistake regarding mounting. 

Now I start again with Bitnami. I will share my results

**Comment by luislobo** [comment]
This https://github.com/bitnami/bitnami-docker-nginx/pull/34 should fix your issues. It now just changes the group permission, not the user ones

**Comment by prydonius** [comment]
Hey guys, the change @luislobo mentioned is released in `bitnami/nginx:1.10.0-r0` and `bitnami/nginx:latest`.
