### ISSUE TITLE
Unable to start NGINX container on RHEL 7.2

### ISSUE THREAD

**Issue by nsamarak** [bitnami/bitnami-docker-nginx#70]
**Repro Steps**
1. Launch a RHEL 7.2 instance on azure
2. Follow the Docker installation directions at https://docs.docker.com/engine/installation/linux/rhel/
3. Run docker run -p 80:80 bitnami/nginx:latest

**Expected Result**
NGINX container starts and is able to answer requests.

**Actual Result**
```
nami    INFO  Initializing nginx
Error executing 'postInstallation': EEXIST: file already exists, symlink '/bitnami/nginx/conf' -> '/opt/bitnami/nginx/conf'
```

**Comment by sameersbn** [comment]
@nsamarak this is because docker-engine installed via instructions from docker.com use the overlayfs storage driver and we have seens repeated issues with our containers when this driver is in use. We recommend using the docker packages from the official centos/rhel distro repos which use the devicemapper storage driver (avoid docker.com packages on these distros).

See the  issues below:
- https://github.com/bitnami/bitnami-docker-mariadb/issues/105#issuecomment-281069943
- https://github.com/bitnami/bitnami-docker-opencart/issues/37

**Comment by sameersbn** [comment]
**Update:**

RHEL treats OverlayFS as a preview filesystem. The following document https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html lists the problems and possible workarounds for using OverlayFS with Docker on RHEL 7.2. 

We hope you find the information contained in this referenced document useful.
