### ISSUE TITLE
Adding reverse proxy

### ISSUE THREAD

**Issue by ric79** [bitnami/bitnami-docker-nginx#90]
Hello,
I have two questions:

1) In section "Adding custom virtual hosts" I think that commas should be added in last two rows.
```
server {
  listen 0.0.0.0:8080;
  server_name www.example.com;
  root /app;
  index index.htm index.html;
}
```

2) I'm using Openshift 3 and I've started the nginx POD. I have also a public route to this POD: http://nginx-my-pod.cloudapp.mycompany.it/.
In that project I have 4 backend apps written in NodeJS (be-app1, be-app2, be-app3, be-app4). I would configure the nginx in order to reverse proxy them. Something like:
```
server  {
  listen  443 ssl;
  server_name http://nginx-my-be-app1.cloudapp.mycompany.it/:
  location  /be-app1/ {
     proxy_pass be-app1;
     proxy_set_header X-Real-IP $remote_addr;
  }
}
```
Is this possible?

**Comment by juan131** [comment]
Hi @ric79 

Regarding the missing commas in the documentation, you're right!! I updated the section and it will be updated once a new version/revision of the Docker Image is released. Thanks for reporting it.

Regarding the second question, yes it's possible! Those NodeJS are running on different PODs, aren't they? You just need to configure a Reverse Proxy to those PODS IP an PORT where the NodeJS app is running. Regarding how to configure NGINX, please refer to the Official Docs:
https://www.nginx.com/resources/admin-guide/reverse-proxy/

**Comment by cima** [comment]
This answer is not very robust. Suppose applications (node.js containers) behind reverse proxy are updated often. Nginx resolves their addresses during the boot time and keeps them forever.  Once you upgrade the node.js application it will appear on different node and gets new IP address (due to openshift's rollout strategy) and since that time it is not reachable over nginx.

To avoid this you need to utilize the `resolver x.x.x.x` directive. Which sadly needs a hostname or ipaddress that is not á priori known due to kubernetes DNS configuration mechanism.

My suggestion is to programatically prepare file resolvers.conf that can be included in virtual hosts configuration files if needed. This file would contain addresses extracted from /etc/resolv.conf where Kubernetes filled a `nameserver x.x.x.x`. Then you can include it where desired.

The solution is de facto ready at stack overflow's answer [Nginx proxy_pass with $remote_addr](https://serverfault.com/questions/638822/nginx-resolver-address-from-etc-resolv-conf)

Would Bitnami be into adding such on the fly generated file which would allow dynamical name resolution in `proxy_pass` directive?

**Comment by juan131** [comment]
> This answer is not very robust. Suppose applications (node.js containers) behind reverse proxy are updated often. Nginx resolves their addresses during the boot time and keeps them forever. Once you upgrade the node.js application it will appear on different node and gets new IP address (due to openshift's rollout strategy) and since that time it is not reachable over nginx.

You could create a **K8s svc** for all those Node.js containers. Therefore, you configure the reverse proxy on NGINX to the svc virtual IP. Then, you don't care what IP is using each of the Node.js pods since K8s will redirect the requests from the svc IP to the POD IP via **iptables** rules.

Is that solution valid for you @cima?

**Comment by cima** [comment]
> Is that solution valid for you @cima?

It is a correct solution to be fair. Our target use case is bit more complicated and still needs more frequent re-resolution as the host names are not known in advance, but it is a temporary workaround for missing API gateway so I wouldn't expand it here. Your proposed solution is correct and lead people to correct network topology.

**Comment by juan131** [comment]
Hi @cima 

Great!! I'm glad the solution works for you!! If you have any other questions/issues, please do not hesitate to let us know!
